server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homework
    username: root
    password: 20031224yyb
    type: com.alibaba.druid.pool.DruidDataSource
  #  dbcp2:
  #    max_idle: 10  #?????
  #    max_total: 50   #???????
  #    max_wait-millis: 100000   #???????????
  #    initial-size: 5  #?????
  #    connectin-properties: characterEncoding=utf8
#  hikari:
#    mininum-idle: 5
#    maxinum-pool-size: 15
#    auto-commit: true
#    idle-timeout: 30000
#    pool-name: DatebookHikariCP
#    max-lifetime: 18000000
#    connection-timeout: 30000
#    connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.springboot.mybatis.demo.mapper: debug
